name: hatebert
channels:
  - conda-forge
  - nvidia # nvidia channel for cuda packages
  - nodefaults
dependencies:
  - python=3.6.10

  # Dev dependencies
  - black
  - isort
  - flake8

  # pip dependencies
  - pip
  - pip:
      - warmup-scheduler

platforms:
  - linux-64
  # - osx-arm64 # This is for M1/M2 MacBooks
  # - linux-aarch64 # This is linux-arm64. We can build Docker images for M1/M2 Macs on top of this - won't support MPS though
  - win-64
